# Construct the context window

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/training/skopje_final_data.csv",low_memory=False)

In [4]:
df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor4_humidity,...,neighbor4_wind_speed,neighbor5_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,1.315275e+06,1.017354e+06,1.014088e+06,1.315275e+06,1.315275e+06,1.315800e+06,1.315275e+06,1.315275e+06,1.315275e+06,1.315275e+06,...,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06
mean,5.566136e+01,2.492260e+01,1.387223e+01,9.828889e+02,1.720202e+01,4.959989e+00,5.530974e+01,5.483988e+01,5.550372e+01,5.499049e+01,...,4.848925e+00,4.847676e+00,-1.850473e-17,-5.551014e-17,-2.785087e-03,-3.554140e-03,-2.996776e-03,-6.839945e-04,2.872777e-01,4.145007e-01
std,1.782989e+01,4.210747e+01,2.289562e+01,9.442534e+00,9.319345e+00,3.199850e+00,1.748186e+01,1.797581e+01,1.810821e+01,1.741685e+01,...,2.876215e+00,2.877265e+00,7.071070e-01,7.071070e-01,7.068597e-01,7.073399e-01,7.073425e-01,7.068648e-01,4.524924e-01,4.926358e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,9.220000e+02,-5.800000e+01,0.000000e+00,0.000000e+00,4.500000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-9.749279e-01,-9.009689e-01,0.000000e+00,0.000000e+00
25%,4.185390e+01,6.000000e+00,3.250000e+00,9.787500e+02,9.703252e+00,2.811690e+00,4.175000e+01,4.100000e+01,4.141880e+01,4.150000e+01,...,2.833955e+00,2.817445e+00,-7.071068e-01,-7.071068e-01,-5.000000e-01,-8.660254e-01,-7.818315e-01,-9.009689e-01,0.000000e+00,0.000000e+00
50%,5.575000e+01,1.200000e+01,6.750000e+00,9.830000e+02,1.641870e+01,4.510787e+00,5.536111e+01,5.450000e+01,5.537326e+01,5.525000e+01,...,4.503598e+00,4.503598e+00,6.123234e-17,-6.123234e-17,0.000000e+00,-1.836970e-16,0.000000e+00,-2.225209e-01,0.000000e+00,0.000000e+00
75%,6.950000e+01,2.766667e+01,1.533333e+01,9.880000e+02,2.432623e+01,6.432324e+00,6.900000e+01,6.850000e+01,6.964757e+01,6.867029e+01,...,6.341009e+00,6.359372e+00,7.071068e-01,7.071068e-01,8.660254e-01,5.000000e-01,7.818315e-01,6.234898e-01,1.000000e+00,1.000000e+00
max,9.900000e+01,1.873750e+03,9.980000e+02,1.195000e+03,5.950000e+01,4.566469e+01,9.900000e+01,9.900000e+01,9.900000e+01,9.900000e+01,...,2.926869e+01,2.926869e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.749279e-01,1.000000e+00,1.000000e+00,1.000000e+00

In [5]:
df.head(10)

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor5_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.916667,NaN,NaN,981.158046,6.359756,7.391761,74.00,75.916667,...,11.246759,winter,0.000000,1.000000e+00,-0.5,0.866025,-0.433884,-0.900969,0,1
1,2023-12-01 01:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.331140,NaN,NaN,981.250000,6.315041,7.238935,73.75,76.331140,...,12.313894,winter,0.258819,9.659258e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
2,2023-12-01 02:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.574786,NaN,NaN,981.250000,6.236111,7.570863,74.50,76.574786,...,10.972620,winter,0.500000,8.660254e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
3,2023-12-01 03:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.818376,NaN,NaN,981.133333,6.378968,7.031864,75.75,76.818376,...,10.233123,winter,0.707107,7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
4,2023-12-01 04:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.098291,NaN,NaN,981.044444,6.593254,6.751236,73.75,77.098291,...,10.739832,winter,0.866025,5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
5,2023-12-01 05:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.581197,NaN,NaN,981.000000,6.569444,7.115020,75.50,77.581197,...,11.019764,winter,0.965926,2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
6,2023-12-01 06:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.589744,NaN,NaN,981.241667,6.738095,6.709050,75.00,77.589744,...,10.296251,winter,1.000000,6.123234e-17,-0.5,0.866025,-0.433884,-0.900969,0,1
7,2023-12-01 07:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.341667,NaN,NaN,981.620968,7.269380,8.655718,76.00,78.341667,...,11.246759,winter,0.965926,-2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
8,2023-12-01 08:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.126984,NaN,NaN,982.054688,8.214015,9.931705,76.25,78.126984,...,11.269782,winter,0.866025,-5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
9,2023-12-01 09:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,70.751938,NaN,NaN,981.532828,11.372222,7.709606,71.00,70.751938,...,9.585739,winter,0.707107,-7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1

In [6]:
PREDICTION_LENGTH = 72
ID_COL = 'sensorId'

In [7]:
ground_truth_df = df.groupby(ID_COL).apply(lambda x: x.iloc[-PREDICTION_LENGTH:]).reset_index(drop=True)

/var/folders/18/8m8jfl3d72v4p728z2p8fn8c0000gn/T/ipykernel_40561/3341968842.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ground_truth_df = df.groupby(ID_COL).apply(lambda x: x.iloc[-PREDICTION_LENGTH:]).reset_index(drop=True)

In [8]:
ground_truth_df

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor5_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2025-11-28 00:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,85.75,1.50,1.00,943.000000,2.25,6.771887,76.478009,76.478009,...,6.206738,autumn,0.000000,1.000000,-0.866025,0.5,-0.433884,-0.900969,0,1
1,2025-11-28 01:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,86.00,1.25,0.75,943.000000,2.00,6.967051,75.749405,75.749405,...,6.681856,autumn,0.258819,0.965926,-0.866025,0.5,-0.433884,-0.900969,0,1
2,2025-11-28 02:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,84.50,0.00,0.00,943.000000,2.00,5.769455,75.334524,75.334524,...,5.269422,autumn,0.500000,0.866025,-0.866025,0.5,-0.433884,-0.900969,0,1
3,2025-11-28 03:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,86.00,0.00,0.00,943.000000,2.00,6.382469,76.017262,76.017262,...,5.241679,autumn,0.707107,0.707107,-0.866025,0.5,-0.433884,-0.900969,0,1
4,2025-11-28 04:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,85.00,0.25,0.00,943.500000,2.75,5.290823,76.342857,76.342857,...,4.846648,autumn,0.866025,0.500000,-0.866025,0.5,-0.433884,-0.900969,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,2025-11-30 19:00:00+00:00,sensor_dev_84941_208,83.00,NaN,NaN,981.371212,7.00,0.663094,80.750000,74.500000,...,0.254558,autumn,-0.965926,0.258819,-0.866025,0.5,-0.781831,0.623490,1,1
5396,2025-11-30 20:00:00+00:00,sensor_dev_84941_208,85.50,NaN,NaN,981.377604,6.75,1.077217,82.250000,78.500000,...,0.360000,autumn,-0.866025,0.500000,-0.866025,0.5,-0.781831,0.623490,1,1
5397,2025-11-30 21:00:00+00:00,sensor_dev_84941_208,88.00,NaN,NaN,981.609375,6.00,0.762645,83.000000,81.000000,...,0.254558,autumn,-0.707107,0.707107,-0.866025,0.5,-0.781831,0.623490,1,1
5398,2025-11-30 22:00:00+00:00,sensor_dev_84941_208,89.50,NaN,NaN,981.594086,6.00,0.961617,84.250000,81.000000,...,0.648999,autumn,-0.500000,0.866025,-0.866025,0.5,-0.781831,0.623490,1,1
5399,2025-11-30 23:00:00+00:00,sensor_dev_84941_208,89.00,NaN,NaN,981.567204,6.00,0.839303,83.000000,82.000000,...,0.569210,autumn,-0.258819,0.965926,-0.866025,0.5,-0.781831,0.623490,1,1

In [9]:
ground_truth_df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor4_humidity,...,neighbor4_wind_speed,neighbor5_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,5400.000000,3880.000000,3880.000000,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000,...,5400.000000,5400.000000,5.400000e+03,5.400000e+03,5400.000000,5400.0,5400.000000,5400.000000,5400.000000,5400.0
mean,72.838251,19.407109,11.129442,979.337253,7.510901,4.068014,72.159663,70.921235,72.629738,70.674951,...,3.867935,3.858715,-1.710566e-17,-5.361966e-17,-0.866025,0.5,-0.730214,-0.166667,0.666667,1.0
std,10.095994,20.460399,11.156869,7.791542,2.699157,2.590725,9.301115,10.895749,10.657740,9.840989,...,2.044466,2.051042,7.071723e-01,7.071723e-01,0.000000,0.0,0.223896,0.623667,0.471448,0.0
min,29.500000,0.000000,0.000000,939.000000,-1.000000,0.180000,29.500000,29.500000,31.500000,29.500000,...,0.180000,0.180000,-1.000000e+00,-1.000000e+00,-0.866025,0.5,-0.974928,-0.900969,0.000000,1.0
25%,67.000000,5.500000,3.000000,978.059456,6.000000,2.174948,66.750000,64.775641,67.750000,65.042406,...,2.167487,2.160000,-7.071068e-01,-7.071068e-01,-0.866025,0.5,-0.974928,-0.900969,0.000000,1.0
50%,74.322368,13.000000,7.500000,980.082465,7.038618,4.155622,73.889640,73.000000,74.519812,73.000000,...,4.107377,4.107377,6.123234e-17,-6.123234e-17,-0.866025,0.5,-0.781831,-0.222521,1.000000,1.0
75%,76.955631,27.750000,16.000000,983.000000,8.620040,5.652114,76.609524,76.432957,76.763072,76.333333,...,5.623380,5.623380,7.071068e-01,7.071068e-01,-0.866025,0.5,-0.433884,0.623490,1.000000,1.0
max,99.000000,395.250000,150.000000,991.000000,21.500000,28.108831,99.000000,99.000000,99.000000,99.000000,...,9.473541,9.473541,1.000000e+00,1.000000e+00,-0.866025,0.5,-0.433884,0.623490,1.000000,1.0

In [10]:
ground_truth_df.isnull().sum()

timestamp                   0
sensorId                    0
humidity                    0
pm10                     1520
pm25                     1520
pressure                    0
temperature                 0
wind_speed                  0
neighbor1_humidity          0
neighbor2_humidity          0
neighbor3_humidity          0
neighbor4_humidity          0
neighbor5_humidity          0
neighbor1_pressure          0
neighbor2_pressure          0
neighbor3_pressure          0
neighbor4_pressure          0
neighbor5_pressure          0
neighbor1_temperature       0
neighbor2_temperature       0
neighbor3_temperature       0
neighbor4_temperature       0
neighbor5_temperature       0
neighbor1_wind_speed        0
neighbor2_wind_speed        0
neighbor3_wind_speed        0
neighbor4_wind_speed        0
neighbor5_wind_speed        0
season                      0
hour_sin                    0
hour_cos                    0
month_sin                   0
month_cos                   0
day_sin                     0
day_cos                     0
is_weekend                  0
is_heating_season           0
dtype: int64

In [11]:
ground_truth_df.to_csv("context_skopje.csv", index=False)