# Construct the context window

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/training/bitola_final_data.csv")

In [3]:
df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,192533.000000,142475.00000,142887.000000,192533.000000,192533.000000,192907.000000,192533.000000,192533.000000,192533.000000,192533.000000,...,192907.000000,192907.000000,1.929840e+05,1.929840e+05,192984.000000,1.929840e+05,192984.000000,192984.000000,192984.000000,192984.000000
mean,52.706427,26.40624,14.096921,939.802395,16.796424,6.075865,52.234773,53.623165,51.226443,943.013828,...,6.174232,6.158097,-1.847380e-17,-5.550655e-17,-0.002785,-3.554140e-03,-0.002997,-0.000684,0.287278,0.414501
std,15.739595,49.61000,26.306709,12.804769,9.168444,3.743897,15.784644,16.410186,15.056326,6.656861,...,3.866399,3.849372,7.071086e-01,7.071086e-01,0.706861,7.073415e-01,0.707344,0.706866,0.452493,0.492637
min,9.500000,0.00000,0.000000,869.000000,-12.000000,0.000000,9.500000,9.500000,9.500000,911.000000,...,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-1.000000,-1.000000e+00,-0.974928,-0.900969,0.000000,0.000000
25%,40.750000,5.25000,2.250000,937.000000,9.666667,3.500000,40.354167,41.314815,39.750000,939.000000,...,3.500000,3.500000,-7.071068e-01,-7.071068e-01,-0.500000,-8.660254e-01,-0.781831,-0.900969,0.000000,0.000000
50%,53.562500,10.75000,5.500000,942.000000,16.000000,5.300000,53.000000,54.468750,52.250000,943.000000,...,5.400000,5.400000,6.123234e-17,-6.123234e-17,0.000000,-1.836970e-16,0.000000,-0.222521,0.000000,0.000000
75%,64.937500,26.00000,14.000000,946.000000,23.750000,7.744444,64.250000,66.000000,63.000000,947.000000,...,7.900000,7.900000,7.071068e-01,7.071068e-01,0.866025,5.000000e-01,0.781831,0.623490,1.000000,1.000000
max,99.000000,1995.00000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,86.750000,971.750000,...,32.800000,32.800000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,0.974928,1.000000,1.000000,1.000000

In [4]:
df.head(10)

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor3_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,58.333333,28.333333,13.666667,943.0,12.000000,8.3,63.645833,63.645833,...,6.98,winter,0.000000,1.000000e+00,-0.5,0.866025,-0.433884,-0.900969,0,1
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.250000,13.750000,5.000000,943.0,12.000000,9.3,64.750000,64.750000,...,7.50,winter,0.258819,9.659258e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,60.000000,10.000000,4.500000,942.5,12.250000,8.3,65.312500,65.312500,...,6.74,winter,0.500000,8.660254e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.250000,9.750000,4.500000,942.0,13.000000,9.4,64.854167,64.854167,...,7.84,winter,0.707107,7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.500000,5.000000,2.000000,942.0,13.000000,9.0,65.062500,65.062500,...,8.32,winter,0.866025,5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
5,2023-12-01 05:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,60.250000,9.000000,4.000000,942.0,13.000000,7.6,66.500000,66.500000,...,6.28,winter,0.965926,2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
6,2023-12-01 06:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.000000,8.000000,3.750000,942.0,13.750000,6.8,66.187500,66.187500,...,5.16,winter,1.000000,6.123234e-17,-0.5,0.866025,-0.433884,-0.900969,0,1
7,2023-12-01 07:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,56.500000,15.500000,7.000000,943.0,15.500000,12.4,63.250000,63.250000,...,8.72,winter,0.965926,-2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
8,2023-12-01 08:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,53.666667,7.333333,2.333333,943.0,16.666667,15.6,59.708333,59.708333,...,11.40,winter,0.866025,-5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
9,2023-12-01 09:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,51.500000,6.500000,1.750000,943.0,17.250000,18.6,55.062500,55.062500,...,14.72,winter,0.707107,-7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1

In [5]:
PREDICTION_LENGTH = 72
ID_COL = 'sensorId'

In [6]:
ground_truth_df = df.groupby(ID_COL).apply(lambda x: x.iloc[-PREDICTION_LENGTH:]).reset_index(drop=True)

/var/folders/18/8m8jfl3d72v4p728z2p8fn8c0000gn/T/ipykernel_28350/3341968842.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ground_truth_df = df.groupby(ID_COL).apply(lambda x: x.iloc[-PREDICTION_LENGTH:]).reset_index(drop=True)

In [7]:
ground_truth_df

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor3_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2025-11-28 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,66.75,2.50,1.500000,941.0,10.00,10.8,65.000000,71.388889,...,10.8,autumn,0.000000,1.000000,-0.866025,0.5,-0.433884,-0.900969,0,1
1,2025-11-28 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,67.75,1.00,0.250000,941.0,10.00,14.1,65.000000,71.472222,...,14.1,autumn,0.258819,0.965926,-0.866025,0.5,-0.433884,-0.900969,0,1
2,2025-11-28 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,67.00,0.75,0.250000,941.0,10.00,12.2,64.500000,71.851852,...,12.2,autumn,0.500000,0.866025,-0.866025,0.5,-0.433884,-0.900969,0,1
3,2025-11-28 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,67.25,0.25,0.000000,941.5,9.25,12.4,65.250000,72.111111,...,12.4,autumn,0.707107,0.707107,-0.866025,0.5,-0.433884,-0.900969,0,1
4,2025-11-28 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,66.25,0.75,0.250000,942.0,9.00,13.5,64.000000,71.703704,...,13.5,autumn,0.866025,0.500000,-0.866025,0.5,-0.433884,-0.900969,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,2025-11-30 19:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,61.75,11.25,6.000000,942.0,9.00,5.9,63.500000,86.500000,...,5.3,autumn,-0.965926,0.258819,-0.866025,0.5,-0.781831,0.623490,1,1
788,2025-11-30 20:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,63.25,9.00,5.666667,942.0,9.00,5.7,63.750000,90.500000,...,5.4,autumn,-0.866025,0.500000,-0.866025,0.5,-0.781831,0.623490,1,1
789,2025-11-30 21:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,63.50,12.00,6.000000,942.5,8.25,5.8,63.333333,94.333333,...,5.4,autumn,-0.707107,0.707107,-0.866025,0.5,-0.781831,0.623490,1,1
790,2025-11-30 22:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,63.75,3.25,2.500000,943.0,7.75,5.6,63.750000,98.000000,...,5.0,autumn,-0.500000,0.866025,-0.866025,0.5,-0.781831,0.623490,1,1
791,2025-11-30 23:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,63.75,1.75,0.750000,943.0,7.00,6.2,64.000000,98.000000,...,4.9,autumn,-0.258819,0.965926,-0.866025,0.5,-0.781831,0.623490,1,1

In [8]:
ground_truth_df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,792.000000,768.000000,768.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,...,792.000000,792.000000,7.920000e+02,7.920000e+02,7.920000e+02,792.0,792.000000,792.000000,792.000000,792.0
mean,70.172338,22.034722,13.440321,932.928265,8.394215,6.549570,68.929918,71.405907,66.605391,938.527213,...,6.808972,6.780951,-1.794300e-17,-5.607187e-17,-8.660254e-01,0.5,-0.730214,-0.166667,0.666667,1.0
std,8.154606,27.705470,18.027212,15.728904,1.732142,3.348531,8.560930,9.831191,5.134081,3.949365,...,3.487408,3.507676,7.075536e-01,7.075536e-01,1.110925e-16,0.0,0.224017,0.624004,0.471702,0.0
min,51.000000,0.000000,0.000000,883.000000,3.000000,0.200000,51.000000,51.000000,51.000000,925.000000,...,0.200000,0.200000,-1.000000e+00,-1.000000e+00,-8.660254e-01,0.5,-0.974928,-0.900969,0.000000,1.0
25%,64.750000,7.750000,4.500000,933.231250,7.500000,4.100000,63.250000,65.000000,63.250000,938.000000,...,4.200000,4.200000,-7.071068e-01,-7.071068e-01,-8.660254e-01,0.5,-0.974928,-0.900969,0.000000,1.0
50%,69.875000,14.000000,8.500000,938.000000,8.250000,5.900000,67.000000,70.308333,66.000000,939.625000,...,6.000000,6.000000,6.123234e-17,-6.123234e-17,-8.660254e-01,0.5,-0.781831,-0.222521,1.000000,1.0
75%,74.361111,25.062500,16.000000,941.000000,9.500000,8.200000,73.250000,74.687500,70.208333,941.000000,...,8.700000,8.700000,7.071068e-01,7.071068e-01,-8.660254e-01,0.5,-0.433884,0.623490,1.000000,1.0
max,99.000000,204.250000,149.000000,947.000000,14.000000,15.700000,99.000000,99.000000,80.250000,943.750000,...,15.700000,15.700000,1.000000e+00,1.000000e+00,-8.660254e-01,0.5,-0.433884,0.623490,1.000000,1.0

In [9]:
ground_truth_df.isnull().sum()

timestamp                 0
sensorId                  0
humidity                  0
pm10                     24
pm25                     24
pressure                  0
temperature               0
wind_speed                0
neighbor1_humidity        0
neighbor2_humidity        0
neighbor3_humidity        0
neighbor1_pressure        0
neighbor2_pressure        0
neighbor3_pressure        0
neighbor1_temperature     0
neighbor2_temperature     0
neighbor3_temperature     0
neighbor1_wind_speed      0
neighbor2_wind_speed      0
neighbor3_wind_speed      0
season                    0
hour_sin                  0
hour_cos                  0
month_sin                 0
month_cos                 0
day_sin                   0
day_cos                   0
is_weekend                0
is_heating_season         0
dtype: int64

In [10]:
ground_truth_df.to_csv("context_bitola.csv", index=False)